apiVersion: harness.io/v1
kind: Component
type: service
identifier: joshthing
name: josh-thing
owner: group:account/Account_Admins
spec:
  lifecycle: unknown
  sourceCode:
    provider: Github
    repoName: harness-fme-opa
    connectorRef: account.joshgh
    branch: main
    monoRepo: false
    url: https://github.com/kleinjoshuaa/harness-fme-opa/tree/main
metadata:
  name: joshthing
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/kleinjoshuaa/harness-fme-opa/tree/main/docs
    harnessfme/mywork: https://app.harness.io/ng/account/AM8HCbDiTXGQNrTIhNl7qQ/module/fme/orgs/default/projects/default_project/org/4ec48f70-bbfd-11f0-88bf-02779340d5f4/ws/ca8ff370-bf17-11f0-9690-ee36d9ebb814/mywork
